"""
train_alignn.py
===============
Multi-task ALIGNN training for CBM-MOF CH4/N2 adsorption property prediction.

Targets (8 total), transform configured by prepare_data.py:
  - Uptake columns: symlog (various τ), log10, or raw (depends on data dir)
  - Qst columns: always raw kJ/mol

  Config serialized to: <data-dir>/transform_config.json
  (generated by prepare_data.py)

Usage:
    # Dry run (100 samples × 5 epochs)
    CUDA_VISIBLE_DEVICES=0 python train_alignn.py --dry-run

    # Full training with specific data directory
    CUDA_VISIBLE_DEVICES=0 python train_alignn.py --data-dir data/alignn_log10

    # BF16 mixed precision (default, saves ~40% VRAM, enables max-atoms=500)
    CUDA_VISIBLE_DEVICES=0 python train_alignn.py --amp-mode bf16 --max-atoms 500

    # Disable AMP (fp32 fallback for debugging)
    CUDA_VISIBLE_DEVICES=0 python train_alignn.py --amp-mode off

AMP notes:
  - bf16  : Safe on RTX 4090 (sm_89). Same exponent range as fp32 → no Inf
            overflow. No GradScaler needed. ~40% VRAM reduction.
  - fp16  : UNSAFE for this project — Qst ~14 kJ/mol × AMP scale 65536 =
            ~1.8M overflows fp16 max (65504) → Inf gradients → never learns.
  - off   : Full fp32. Fallback for debugging or non-BF16 hardware.
"""

import argparse
import json
import os
import pickle as pk
import time
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import dgl
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Subset

warnings.filterwarnings("ignore", category=UserWarning)

# ──────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────
REPO_ROOT     = Path("/home/zhangsd/repos/CBM-MOF")
ALIGNN_DATA   = REPO_ROOT / "data/alignn"
RESULTS_DIR   = REPO_ROOT / "results/alignn"
CIF_DIR       = ALIGNN_DATA / "cifs"

UPTAKE_COLS   = ["AdsCH4_10kPa", "AdsCH4_100kPa", "AdsCH4_1000kPa",
                 "AdsN2_10kPa",  "AdsN2_100kPa",  "AdsN2_1000kPa"]
QST_COLS      = ["QstCH4", "QstN2"]
TARGET_COLS   = UPTAKE_COLS + QST_COLS
N_TARGETS     = len(TARGET_COLS)


# ──────────────────────────────────────────────────────────────
# Metrics
# ──────────────────────────────────────────────────────────────
def compute_metrics(pred: np.ndarray, true: np.ndarray, tag: str = ""):
    """Compute MAE and R² in the training (transformed) space.

    Note: id_prop.csv targets are already per-column symlog-transformed for
    uptake columns and raw kJ/mol for Qst columns.  We report MAE in that
    same transformed space (no additional inverse transform) to keep units
    consistent with how the model is trained.
    """
    results = {}
    for i, col in enumerate(TARGET_COLS):
        y_p = pred[:, i]
        y_t = true[:, i]
        mae = np.mean(np.abs(y_p - y_t))
        ss_res = np.sum((y_t - y_p) ** 2)
        ss_tot = np.sum((y_t - np.mean(y_t)) ** 2)
        r2 = 1 - ss_res / (ss_tot + 1e-12)
        results[col] = {"MAE": float(mae), "R2": float(r2)}
        if tag:
            unit = "symlog" if col in UPTAKE_COLS else "kJ/mol"
            print(f"  [{tag}] {col:25s}  MAE={mae:.4f} {unit}  R²={r2:.4f}")
    return results


# ──────────────────────────────────────────────────────────────
# Dataset
# ──────────────────────────────────────────────────────────────
def load_dataset(split: str, data_dir: Path = None,
                 dry_run: bool = False, dry_run_size: int = 100,
                 max_atoms: int = 0):
    """
    Load ALIGNN dataset for the given split.

    Args:
        split: 'train', 'val', or 'test'
        data_dir: root data directory containing {split}/id_prop.csv and cifs/
        dry_run: if True, use only dry_run_size samples
        dry_run_size: number of samples for dry run
        max_atoms: filter out structures with more atoms (0=disabled)

    API updated for alignn >= 2025.x:
      - StructureDataset now lives in alignn.graphs
      - Graphs must be pre-built via alignn.dataset.load_graphs
      - Multi-task targets stored as list in df['target'] column
    """
    from alignn.dataset import load_graphs
    from alignn.graphs import StructureDataset
    from jarvis.core.atoms import Atoms

    if data_dir is None:
        data_dir = ALIGNN_DATA
    cif_dir = data_dir / "cifs"

    id_prop_csv = data_dir / split / "id_prop.csv"
    if not id_prop_csv.exists():
        raise FileNotFoundError(f"Missing: {id_prop_csv}  — run prepare_data.py first")

    df = pd.read_csv(id_prop_csv)
    if dry_run:
        df = df.head(dry_run_size)
        print(f"  DRY RUN: using {len(df)} samples from {split}")

    # Build jarvis-format records
    records = []
    missing = []
    for _, row in df.iterrows():
        mol_id = row["mol_id"]
        cif_path = cif_dir / f"{mol_id}.cif"
        if not cif_path.exists():
            missing.append(mol_id)
            continue
        atoms = Atoms.from_cif(str(cif_path), use_cif2cell=False)
        if max_atoms > 0 and atoms.num_atoms > max_atoms:
            continue  # skip structures that exceed CUDA / memory budget
        records.append({
            "jid":    mol_id,
            "atoms":  atoms.to_dict(),
            "target": row[TARGET_COLS].tolist(),
        })
    if missing:
        print(f"  WARNING: {len(missing)} CIF files not found in {split} split")
    print(f"  Loaded {len(records)} CIF structures for {split}")

    # Build graphs with pickle cache
    # NOTE: alignn 2025.4.1 bug: cachedir parameter calls .tolist() on an
    # already-list input → TypeError. We use our own pickle cache instead.
    cache_dir = data_dir / "cache" / split
    cache_dir.mkdir(parents=True, exist_ok=True)
    cache_tag = f"maxatoms{max_atoms}" if max_atoms > 0 else "all"
    cache_file = cache_dir / f"graphs_{cache_tag}_cache.pkl"

    df_records = pd.DataFrame(records)

    if cache_file.exists():
        print(f"  Loading cached graphs from {cache_file}")
        graphs = pk.load(open(cache_file, "rb"))
    else:
        graphs = load_graphs(
            df_records,
            neighbor_strategy="k-nearest",
            cutoff=8.0,
            cutoff_extra=3.0,
            max_neighbors=12,
            cachedir=None,  # disabled: bug in alignn 2025.4.1
            use_canonize=False,
            id_tag="jid",
        )
        pk.dump(graphs, open(cache_file, "wb"))
        print(f"  Graph cache saved to {cache_file}")

    # Build dataset with line graphs and cgcnn atom features
    dataset = StructureDataset(
        df_records,
        graphs,
        target="target",
        atom_features="cgcnn",
        line_graph=True,
        id_tag="jid",
    )
    return dataset


# ──────────────────────────────────────────────────────────────
# Model
# ──────────────────────────────────────────────────────────────
def build_model(config: dict) -> nn.Module:
    """Build ALIGNN model with multi-task output head.

    Note: alignn >= 2025.x renamed n_layers → gcn_layers and removed
    compute_line_graph / atom_features from ALIGNNConfig.
    """
    from alignn.models.alignn import ALIGNN, ALIGNNConfig

    alignn_cfg = ALIGNNConfig(
        name="alignn",
        atom_input_features=92,
        edge_input_features=config.get("edge_input_features", 80),
        triplet_input_features=config.get("triplet_input_features", 40),
        embedding_features=config.get("embedding_features", 64),
        hidden_features=config.get("hidden_features", 256),
        output_features=N_TARGETS,            # 8 multi-task outputs
        gcn_layers=config.get("n_layers", 4),     # renamed from n_layers
        alignn_layers=config.get("alignn_layers", 4),
        link=config.get("link", "identity"),
    )
    model = ALIGNN(alignn_cfg)
    return model


# ──────────────────────────────────────────────────────────────
# Training loop
# ──────────────────────────────────────────────────────────────
def train_epoch(model, loader, optimizer, device, amp_mode: str = "off"):
    """Train one epoch with optional BF16 mixed precision.

    Args:
        amp_mode: 'bf16'  — BF16 autocast (recommended; same exponent range as
                            fp32, no GradScaler needed, ~40% VRAM reduction).
                  'off'   — Full fp32 (legacy default, safe on all hardware).
                  'fp16'  — NOT RECOMMENDED: overflows for this project because
                            Qst ~14 kJ/mol × AMP scale 65536 > fp16 max.

    BF16 safety rationale:
      - BF16 max value ≈ 3.39e38 (identical exponent to fp32).
      - z-score normalised targets have mean=0, std=1 → no large-value risk.
      - RTX 4090 (sm_89) has native BF16 Tensor Core support.
      - No GradScaler required: BF16 underflow probability is negligible.
    """
    model.train()
    total_loss = 0.0
    criterion  = nn.MSELoss()
    use_amp    = amp_mode == "bf16"

    for batch in loader:
        g, lg, lat, targets = batch
        g   = g.to(device)
        lg  = lg.to(device)
        lat = lat.to(device)
        targets = targets.to(device).float()

        optimizer.zero_grad()
        with torch.amp.autocast("cuda", dtype=torch.bfloat16, enabled=use_amp):
            preds = model((g, lg, lat))
            loss  = criterion(preds, targets)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        total_loss += loss.item() * len(targets)

    return total_loss / len(loader.dataset)


@torch.no_grad()
def eval_epoch(model, loader, device, amp_mode: str = "off"):
    """Evaluate one epoch.  BF16 autocast also reduces inference VRAM."""
    model.eval()
    preds_list   = []
    targets_list = []
    use_amp      = amp_mode == "bf16"

    for batch in loader:
        g, lg, lat, targets = batch
        g   = g.to(device)
        lg  = lg.to(device)
        lat = lat.to(device)
        targets = targets.float()
        with torch.amp.autocast("cuda", dtype=torch.bfloat16, enabled=use_amp):
            preds = model((g, lg, lat)).cpu()
        preds_list.append(preds.float().numpy())   # cast back to fp32 for metrics
        targets_list.append(targets.numpy())

    return np.vstack(preds_list), np.vstack(targets_list)


# ──────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="Multi-task ALIGNN training for CBM-MOF")
    parser.add_argument("--dry-run",      action="store_true",
                        help="Use 100 samples × 5 epochs for pipeline verification")
    parser.add_argument("--dry-run-size", type=int, default=100)
    parser.add_argument("--max-atoms",    type=int, default=0,
                        help="Filter out structures with more than N atoms (0 = disabled)")
    parser.add_argument("--epochs",       type=int, default=500)
    parser.add_argument("--batch-size",   type=int, default=64)
    parser.add_argument("--lr",           type=float, default=1e-3)
    parser.add_argument("--data-dir",     type=str, default=None,
                        help="Path to data directory (default: data/alignn/)")
    parser.add_argument("--output-dir",   type=str,
                        default=str(RESULTS_DIR))
    parser.add_argument("--output-tag",   type=str, default=None,
                        help="Override the auto-generated output subdirectory tag")
    parser.add_argument("--config",       type=str, default=None,
                        help="Path to JSON config (overrides defaults)")
    parser.add_argument("--amp-mode",     type=str, default="bf16",
                        choices=["off", "bf16", "fp16"],
                        help="Mixed precision mode: bf16 (default, ~40%% VRAM reduction), "
                             "off (fp32 fallback), fp16 (unsafe—overflows for this project)")
    args = parser.parse_args()

    # ── Config ──────────────────────────────────────────────
    default_cfg = dict(
        hidden_features=256,
        embedding_features=64,
        edge_input_features=80,
        triplet_input_features=40,
        n_layers=4,
        alignn_layers=4,
        atom_features="cgcnn",
        link="identity",
    )
    if args.config:
        with open(args.config) as f:
            default_cfg.update(json.load(f))
    cfg = default_cfg

    # ── Dry-run overrides ───────────────────────────────────
    epochs     = 5 if args.dry_run else args.epochs
    batch_size = args.batch_size

    # ── Output dir ─────────────────────────────────────────
    if args.output_tag:
        tag = args.output_tag
    else:
        tag = f"dryrun_{args.dry_run_size}" if args.dry_run else "full"
    output_dir = Path(args.output_dir) / tag
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"Output dir: {output_dir}")

    # ── Device ──────────────────────────────────────────────
    device  = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    n_gpus  = torch.cuda.device_count()
    amp_mode = args.amp_mode
    print(f"Device: {device} ({n_gpus} GPU(s) visible)")
    if amp_mode == "bf16":
        bf16_ok = torch.cuda.is_available() and torch.cuda.is_bf16_supported()
        print(f"AMP mode : bf16 (hardware support: {bf16_ok})")
        if not bf16_ok:
            print("WARNING: BF16 not supported on this GPU — falling back to fp32")
            amp_mode = "off"
    elif amp_mode == "fp16":
        print("WARNING: fp16 AMP is unsafe for this project (Qst overflow). "
              "Use --amp-mode bf16 or off.")
    else:
        print("AMP mode : off (fp32)")

    # ── Data dir ─────────────────────────────────────────────
    data_dir = Path(args.data_dir) if args.data_dir else ALIGNN_DATA
    print(f"\nData directory: {data_dir}")

    # ── Data ────────────────────────────────────────────────
    print("Loading datasets...")
    train_data = load_dataset("train", data_dir=data_dir, dry_run=args.dry_run, dry_run_size=args.dry_run_size, max_atoms=args.max_atoms)
    val_data   = load_dataset("val",   data_dir=data_dir, dry_run=args.dry_run, dry_run_size=min(50, args.dry_run_size), max_atoms=args.max_atoms)
    print(f"  train: {len(train_data)}, val: {len(val_data)}")

    # ── Z-score target normalization ────────────────────────
    # Qst columns (raw kJ/mol, mean≈14/11) dominate MSE at ~75% while
    # symlog uptake columns (scale ~0–2) only contribute ~25%.  Without
    # normalization the model ignores uptake signal entirely.
    # Compute stats from training labels only; apply same transform to val.
    train_labels = train_data.labels          # shape (N_train, 8)
    target_mean  = train_labels.mean(dim=0)   # (8,)
    target_std   = train_labels.std(dim=0).clamp(min=1e-6)  # (8,)
    print("  Target normalization (z-score from training set):")
    for i, col in enumerate(TARGET_COLS):
        print(f"    {col:30s}  mean={target_mean[i]:8.4f}  std={target_std[i]:8.4f}")

    # Normalize in-place (these tensors are not used elsewhere)
    train_data.labels = (train_data.labels - target_mean) / target_std
    val_data.labels   = (val_data.labels   - target_mean) / target_std

    # Save normalization stats alongside model checkpoints
    norm_stats = {"mean": target_mean.tolist(), "std": target_std.tolist(),
                  "columns": TARGET_COLS}

    def collate_fn(samples):
        """Custom collate: always returns (g, lg, lat, labels).

        alignn 2025.x collate_line_graph drops lattice for multi-dim labels;
        we override it so model((g, lg, lat)) always receives all three graphs.
        """
        graphs, line_graphs, lattices, labels = map(list, zip(*samples))
        batched_g  = dgl.batch(graphs)
        batched_lg = dgl.batch(line_graphs)
        return batched_g, batched_lg, torch.stack(lattices), torch.stack(labels)
    train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True,
                              num_workers=4, pin_memory=True,
                              collate_fn=collate_fn)
    val_loader   = DataLoader(val_data, batch_size=batch_size, shuffle=False,
                              num_workers=4, pin_memory=True,
                              collate_fn=collate_fn)

    # ── Model ───────────────────────────────────────────────
    print("\nBuilding ALIGNN model...")
    model = build_model(cfg)
    # NOTE: DGL graphs do NOT support PyTorch DataParallel (graphs stay on
    # cuda:0 while replicas run on other devices → DGLError on first forward).
    # Single-GPU training is used here. Multi-GPU training requires DDP.
    model = model.to(device)
    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"  Trainable parameters: {n_params:,}")

    # ── Optimizer / Scheduler ───────────────────────────────
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-5)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    # ── Training ────────────────────────────────────────────
    history   = []
    best_val_mae = float("inf")
    best_ckpt = output_dir / "best_model.pt"

    print(f"\n{'Epoch':>6} {'train_loss':>12} {'val_MAE_mean':>14} {'time':>8}")
    print("-" * 48)

    for epoch in range(1, epochs + 1):
        t0 = time.time()
        train_loss = train_epoch(model, train_loader, optimizer, device, amp_mode)
        scheduler.step()

        val_preds, val_true = eval_epoch(model, val_loader, device, amp_mode)
        metrics = compute_metrics(val_preds, val_true)
        val_mae_mean = np.mean([v["MAE"] for v in metrics.values()])

        elapsed = time.time() - t0
        print(f"{epoch:6d} {train_loss:12.5f} {val_mae_mean:14.5f} {elapsed:8.1f}s")

        record = {"epoch": epoch, "train_loss": train_loss, "val_mae_mean": val_mae_mean}
        for col, m in metrics.items():
            record[f"val_MAE_{col}"]   = m["MAE"]
            record[f"val_R2_{col}"]    = m["R2"]
        history.append(record)

        # Save best checkpoint
        if val_mae_mean < best_val_mae:
            best_val_mae = val_mae_mean
            torch.save({
                "epoch":       epoch,
                "model_state": (model.module if hasattr(model, "module") else model).state_dict(),
                "optimizer":   optimizer.state_dict(),
                "val_mae":     val_mae_mean,
                "norm_stats":  norm_stats,  # target normalization constants
                "metrics":    metrics,
                "config":     cfg,
            }, best_ckpt)

        # Save latest checkpoint every 10 epochs
        if epoch % 10 == 0 or epoch == epochs:
            torch.save({
                "epoch":      epoch,
                "model_state": (model.module if hasattr(model, "module") else model).state_dict(),
                "optimizer":  optimizer.state_dict(),
            }, output_dir / f"checkpoint_epoch{epoch:04d}.pt")

    # ── Save history ────────────────────────────────────────
    hist_df = pd.DataFrame(history)
    hist_df.to_csv(output_dir / "training_history.csv", index=False)
    print(f"\n✓ Training complete! Best val MAE: {best_val_mae:.5f}")
    print(f"  Best model: {best_ckpt}")

    # ── Final evaluation on best model ──────────────────────
    print("\nFinal evaluation on val set (best model):")
    ckpt = torch.load(best_ckpt, map_location=device)
    base_model = model.module if hasattr(model, "module") else model
    base_model.load_state_dict(ckpt["model_state"])
    val_preds, val_true = eval_epoch(model, val_loader, device, amp_mode)
    final_metrics = compute_metrics(val_preds, val_true, tag="val")
    with open(output_dir / "final_metrics.json", "w") as f:
        json.dump(final_metrics, f, indent=2)
    print(f"  Metrics saved: {output_dir}/final_metrics.json")


if __name__ == "__main__":
    main()
