"""Generate SuperPSA ProcessConfig.yaml adapted for CH4/N2 separation.

Library module — called by select_optimization_candidates.py.

Adapts the CO2/N2 ProcessConfig.yaml template to CH4/N2-specific constants and bounds.

Public API:
  - load_template(path) -> dict
  - adapt_for_ch4_n2(config, mode, ldf_coefficients) -> dict
  - write_config(config, path) -> None
"""

from __future__ import annotations

import copy
import logging
from pathlib import Path

import yaml

from convert_params_for_superpsa import compute_ldf_coefficients

logger = logging.getLogger(__name__)

# Default template: SuperPSA's existing ProcessConfig.yaml
_SUPERPSA_ROOT = Path(__file__).resolve().parents[2] / "SuperPSA"
_DEFAULT_TEMPLATE = _SUPERPSA_ROOT / "data" / "ProcessConfig.yaml"

# CH4/N2-specific physical constants (298.15 K, 1 atm)
CH4_N2_CONSTANTS = {
    "T_0": 298.15,       # Feed temperature [K]
    "y_0": 0.20,         # CH4 mole fraction in CBM feed
    "MW_CO2": 0.01604,   # Actually MW_CH4 [kg/mol]; key kept for MATLAB compat
    "MW_N2": 0.02802,    # N2 molecular weight [kg/mol]
    "mu": 1.75e-5,       # Mixture viscosity at 298K [Pa*s]
    "C_pg": 29.1,        # Gas heat capacity [J/mol/K] (CH4/N2 mixture at 298K)
    "C_pa": 29.1,        # Adsorbed phase heat capacity [J/mol/K]
}

# NSGA-II bounds for PSA mode
# x(1)=P_H [Pa], x(6)=P_L [Pa]
PSA_BOUNDS = {
    "lb": [100000,   10,  0.0,  0.05, 0.0, 100000,  10,  10,  0, 0],
    "ub": [1000000, 5000, 0.5,  0.50, 0.0, 100000, 300, 300,  0, 0],
}

# NSGA-II bounds for VSA mode
VSA_BOUNDS = {
    "lb": [100000,   10,  0.0,  0.05, 0.0, 10000,  10,  10,  0, 0],
    "ub": [100000, 5000, 0.5,  0.50, 0.0, 100000, 300, 300,  0, 0],
}


def load_template(template_path: Path) -> dict:
    """Load the YAML template preserving structure.

    Args:
        template_path: Path to the template ProcessConfig.yaml.

    Returns:
        Parsed YAML as nested dict.
    """
    with open(template_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)
    logger.info("Loaded template from %s", template_path)
    return config


def adapt_for_ch4_n2(
    config: dict,
    mode: str,
    ldf_coefficients: dict[str, float] | None = None,
) -> dict:
    """Adapt a CO2/N2 ProcessConfig for CH4/N2 separation.

    Args:
        config: Template config dict (will be deep-copied).
        mode: "PSA" or "VSA".
        ldf_coefficients: Dict with k_CH4_LDF and k_N2_LDF [1/s].
            If None, will be computed from default transport params.

    Returns:
        Modified config dict for CH4/N2 separation.
    """
    cfg = copy.deepcopy(config)
    mode = mode.upper()
    if mode not in ("PSA", "VSA"):
        raise ValueError(f"mode must be 'PSA' or 'VSA', got '{mode}'")

    # Compute LDF if not provided
    if ldf_coefficients is None:
        ldf_coefficients = compute_ldf_coefficients(
            T=298.0, P_bar=1.0,
            r_p=1e-3, d_pore=1e-9,
            epsilon_p=0.35, tau_p=3.0,
        )

    # Update physical constants
    phys = cfg["physical_constants"]
    for key, val in CH4_N2_CONSTANTS.items():
        phys[key] = val
    phys["D_m"] = float(f"{ldf_coefficients['D_m']:.6e}")

    # Update adsorbent bed LDF coefficients
    bed = cfg["adsorbent_bed"]
    bed["k_CO2_LDF"] = float(round(ldf_coefficients["k_CH4_LDF"], 6))  # "CO2" = CH4
    bed["k_N2_LDF"] = float(round(ldf_coefficients["k_N2_LDF"], 6))

    # Update optimization bounds
    opt = cfg["optimization_settings"]
    if mode == "PSA":
        bounds = PSA_BOUNDS
    else:
        bounds = VSA_BOUNDS
    opt["lb"] = bounds["lb"]
    opt["ub"] = bounds["ub"]

    logger.info("Adapted config for %s mode (CH4/N2, 298.15K)", mode)
    return cfg


def write_config(config: dict, output_path: Path) -> None:
    """Write config dict to YAML with comments.

    Uses inline format for lists so that loadParamsYAML.m's extractArray()
    can parse them (expects ``[val1, val2, ...]`` on a single line).

    Args:
        config: Config dict to write.
        output_path: Output file path.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Build YAML string with inline comments for the optimization bounds
    header = (
        "# ProcessConfig.yaml\n"
        "# CH4/N2 PSA/VSA simulation configuration for CBM-MOF screening\n"
        "# Auto-generated by generate_process_config.py\n"
        "#\n"
        "# NOTE: SuperPSA MATLAB reads key names literally.\n"
        "#   MW_CO2 -> actually MW_CH4 (0.01604 kg/mol)\n"
        "#   k_CO2_LDF -> actually k_CH4_LDF\n"
        "#   deltaU_CO2 -> actually deltaU_CH4\n"
        "\n"
    )

    footer = (
        "\n"
        "# x(1)                                    % Adsorption pressure [Pa]\n"
        "# x(2)                                    % Adsorption step time [s]\n"
        "# x(3)                                    % Light product reflux ratio [-]\n"
        "# x(4)                                    % Feed velocity [m/s]\n"
        "# x(5)                                    % HR1 heavy product reflux ratio [-]\n"
        "# x(6)                                    % Purge pressure [Pa]\n"
        "# x(7)                                    % Pressurization step time [s]\n"
        "# x(8)                                    % CnC depressurization step time [s]\n"
        "# x(9)                                    % CoC depressurization step time [s]\n"
        "# x(10)                                   % HR2 heavy product reflux ratio [-]\n"
        "\n"
        "# Material isotherm parameters stored in data/Adsorbents.csv.\n"
        "# CSV format: col1 material_name, col2-14 IsothermPar, col15-17 SimParam\n"
    )

    # Custom representer: emit lists in flow style [a, b, c] on one line
    class _InlineListDumper(yaml.SafeDumper):
        pass

    def _list_representer(dumper: yaml.SafeDumper, data: list) -> yaml.Node:
        return dumper.represent_sequence(
            "tag:yaml.org,2002:seq", data, flow_style=True
        )

    _InlineListDumper.add_representer(list, _list_representer)

    yaml_body = yaml.dump(
        config,
        Dumper=_InlineListDumper,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=120,
    )

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(yaml_body)
        f.write(footer)

    logger.info("Wrote config to %s", output_path)


_DEFAULT_TEMPLATE_PATH = _DEFAULT_TEMPLATE  # re-export for callers
